""" added breed cokulmn

Revision ID: 984d6a452e50
Revises: 
Create Date: 2021-11-02 22:45:35.160113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984d6a452e50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'breed')
    # ### end Alembic commands ###
